FROM ruby:2.7.2

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV BUNDLE_VERSION 2.1.4
 
RUN apt-get update -qq && apt-get install -y --force-yes build-essential \
    curl git nodejs yarn
 
COPY Gemfile /usr/src/app/
COPY Gemfile.lock /usr/src/app/

RUN gem install bundler --version "$BUNDLE_VERSION" \
&& rm -rf $GEM_HOME/cache/* 

RUN bundle install

COPY . /usr/src/app

ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]