version: '3.8'
 
services:
    db:
        image: postgres:12.5-alpine
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        environment:
            POSTGRES_PASSWORD: password
    triage:
        depends_on:
        - 'db'
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: rake db:create db:schema:load db:seed
        ports:
        - '3000:3000'
        volumes:
        - '.:/usr/src/app'
    redis:
        image: redis:latest
        command: redis-server
    sidekiq:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: bundle exec sidekiq
        depends_on:
            - redis
            - db
        volumes:
            - '.:/usr/src/app'
        env_file:
            - .env
        entrypoint: ./entrypoints/sidekiq-entrypoint.sh
    
volumes:
  postgres:
